default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kamerie_development
  username: kamerie
  password: password

test:
  <<: *default
  database: kamerie_test
  username: kamerie
  password: password

production:
  <<: *default
  database: kamerie_production
  username: kamerie
  password: password
