default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: redmarker_development
  username: redmarker
  password: password

test:
  <<: *default
  database: redmarker_test
  username: redmarker
  password: password

production:
  <<: *default
  database: redmarker_production
  username: redmarker
  password: password
